
CREATE TABLE [PRODUTOS]
([CÓDIGO] VARCHAR(10) NOT NULL,
[DESCRITOR] VARCHAR(100) NULL,
[SABOR] VARCHAR(50) NULL,
[TAMANHO] VARCHAR(50) NULL,
[EMBALAGEM] VARCHAR(50) NULL,
[PREÇO LISTA] FLOAT NULL,
CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED ([CÓDIGO]))

CREATE TABLE [VENDEDORES]
([MATRÍCULA] VARCHAR(5) NOT NULL,
[NOME] VARCHAR(100) NULL,
[BAIRRO] VARCHAR(50) NULL,
[COMISSÃO] FLOAT NULL,
[DATA ADMISSÃO] DATE NULL,
[FÉRIAS] BIT NULL,
CONSTRAINT [PK_VENDEDORES] PRIMARY KEY CLUSTERED ([MATRÍCULA]))

CREATE TABLE [CLIENTES]
([CPF] VARCHAR(11) NOT NULL,
[NOME] VARCHAR(100) NULL,
[ENDEREÇO] VARCHAR(150) NULL,
[BAIRRO] VARCHAR(50) NULL,
[CIDADE] VARCHAR(50) NULL,
[ESTADO] VARCHAR(50) NULL,
[CEP] VARCHAR(8) NULL,
[DATA NASCIMENTO] DATE NULL,
[IDADE] INT,
[SEXO] VARCHAR(1) NULL,
[LIMITE CRÉDITO] FLOAT NULL,
[VOLUME COMPRA] FLOAT NULL,
[PRIMEIRA COMPRA] BIT NULL,
CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED ([CPF]))


CREATE TABLE [dbo].[ITENS VENDIDOS](
	[NÚMERO] [varchar](5) NOT NULL,
	[CÓDIGO PRODUTO] [VARCHAR](10) NULL,
	[QUANTIDADE] [INT] NULL,
	[PREÇO] [float] NULL,
 CONSTRAINT [PK_ITENS_VENDIDOS] PRIMARY KEY CLUSTERED 
([NÚMERO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

-----------------------------------------------------------

ALTER TABLE [NOTAS] WITH CHECK ADD CONSTRAINT [FK_NOTAS_CLIENTES]
FOREIGN KEY([CPF]) REFERENCES [CLIENTES] ([CPF])

ALTER TABLE [dbo].[NOTAS]  WITH CHECK ADD  CONSTRAINT [FK_NOTAS_VENDEDORES] FOREIGN KEY([MATRÍCULA])
REFERENCES [dbo].[VENDEDORES] ([MATRÍCULA])

ALTER TABLE [dbo].[ITENS VENDIDOS]  WITH CHECK ADD  CONSTRAINT [FK_ITENS VENDIDOS_NOTAS] FOREIGN KEY([NÚMERO])
REFERENCES [dbo].[NOTAS] ([NÚMERO])

ALTER TABLE [dbo].[ITENS VENDIDOS]  WITH CHECK ADD  CONSTRAINT [FK_ITENS VENDIDOS_PRODUTOS] FOREIGN KEY([CÓDIGO])
REFERENCES [dbo].[PRODUTOS] ([CÓDIGO])

-----------------------------------------------------------

select * from PRODUTOS

INSERT INTO [PRODUTOS]
([CÓDIGO],[DESCRITOR],[SABOR],[TAMANHO],[EMBALAGEM],[PREÇO LISTA])
VALUES
('1040107','Light - 350 ml - Melância', 'Melância', '350 ml','Lata', 4.56),
('1040108','Light - 350 ml - Graviola', 'Graviola', '350 ml','Lata', 4.00),
('1040109','Light - 350 ml - Açai', 'Açai', '350 ml','Lata', 5.60),
('1040110','Light - 350 ml - Jaca', 'Jaca', '350 ml','Lata', 6.00),
('1040111','Light - 350 ml - Manga', 'Manga', '350 ml','Lata', 3.50)

select * from PRODUTOS

select * from CLIENTES

INSERT INTO [dbo].[CLIENTES]
           ([CPF],[NOME],[ENDEREÇO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA NASCIMENTO],[IDADE],[SEXO],[LIMITE CRÉDITO],[VOLUME COMPRA],[PRIMEIRA COMPRA])
     VALUES
           ('1471156710', 'Érica Carvalho', 'R. Iriquitia', 'Jardins', 'São Paulo', 'SP', '80012212', '1990-09-01'
           ,27, 'F', 170000.0, 24500.0, 0),
		   ('19290992743', 'Fernando Cavalcante', 'R. Dois de Fevereiro', 'Água Santa', 'Rio de Janeiro', 'RJ', '22000000', '20000212'
           ,18, 'M', 100000.0, 20000.0, 1),
		   ('2600586709', 'César Teixeira', 'Rua Conde de Bonfim', 'Tijuca', 'Rio de Janeiro', 'RJ', '22020001', '20000312'
           ,18, 'M', 120000.0, 22000.0, 0)


select * from [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]

select * from PRODUTOS

insert into PRODUTOS (CÓDIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, [PREÇO LISTA])
select TP.[CODIGO DO PRODUTO] AS 'CÓDIGO', TP.[NOME DO PRODUTO] AS 'DESCRITOR', TP.SABOR, TP.TAMANHO, TP.EMBALAGEM, TP.[PREÇO DE LISTA] AS 'PREÇO LISTA'
from [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS] TP
where not TP.[CODIGO DO PRODUTO] = '1040107'

select * from [SUCOS_VENDAS].[dbo].[TABELA DE CLIENTES]

select * from CLIENTES

INSERT INTO CLIENTES (CPF, NOME, ENDEREÇO, BAIRRO, CIDADE, ESTADO, CEP, [DATA NASCIMENTO], IDADE, SEXO, [LIMITE CRÉDITO], [VOLUME COMPRA], [PRIMEIRA COMPRA])
select TC.CPF, TC.NOME, TC.[ENDERECO 1] AS 'ENDEREÇO', TC.BAIRRO, TC.CIDADE, TC.ESTADO, TC.CEP, TC.[DATA DE NASCIMENTO] AS 'DATA NASCIMENTO', TC.IDADE, TC.SEXO,
TC.[LIMITE DE CREDITO] AS 'LIMITE CRÉDITO', TC.[VOLUME DE COMPRA] AS 'VOLUME COMPRA', TC.[PRIMEIRA COMPRA]
FROM [SUCOS_VENDAS].[dbo].[TABELA DE CLIENTES] TC
WHERE TC.CPF NOT IN ('1471156710', '19290992743', '2600586709')

INSERT INTO [dbo].[CLIENTES]
           ([CPF],[NOME],[ENDEREÇO],[BAIRRO],[CIDADE],[ESTADO],[CEP],[DATA NASCIMENTO],[IDADE],[SEXO],[LIMITE CRÉDITO],[VOLUME COMPRA],[PRIMEIRA COMPRA])
     VALUES
           (9999999999,'Matheus Jesus','R. Nova 23','Jardins','São Paulo','SP','80012212','19930701',24,'M',12000,30000,0)

SELECT * FROM PRODUTOS

UPDATE CLIENTES SET
ENDEREÇO = 'R. Jorge Emilio 23', 
BAIRRO = 'Santo Amaro',
CIDADE = 'São Paulo',
ESTADO = 'SP',
CEP = '8833223'
WHERE CPF = '19290992743'

SELECT * FROM CLIENTES WHERE ESTADO = 'RJ'

UPDATE CLIENTES SET
[VOLUME COMPRA] = [VOLUME COMPRA] * 1.20
WHERE ESTADO = 'RJ'

SELECT * FROM CLIENTES WHERE ESTADO = 'RJ'

SELECT * FROM [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]

UPDATE [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS] SET
[PREÇO DE LISTA] = 7
WHERE [CODIGO DO PRODUTO] = '1000889'

UPDATE A SET A.[PREÇO LISTA] = B.[PREÇO DE LISTA]
FROM [PRODUTOS] A INNER JOIN [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS] B
ON A.[CÓDIGO] = B.[CODIGO DO PRODUTO]
WHERE A.[CÓDIGO] = '1000889'

SELECT * FROM PRODUTOS

SELECT C.NOME, C.[VOLUME COMPRA]
FROM 
VENDEDORES V INNER JOIN CLIENTES C 
ON V.BAIRRO = C.BAIRRO

UPDATE C SET C.[VOLUME COMPRA] = C.[VOLUME COMPRA] * 1.3
FROM 
VENDEDORES V INNER JOIN CLIENTES C 
ON V.BAIRRO = C.BAIRRO

SELECT C.NOME, C.[VOLUME COMPRA]
FROM 
VENDEDORES V INNER JOIN CLIENTES C 
ON V.BAIRRO = C.BAIRRO

SELECT * FROM [SUCOS_VENDAS].dbo.[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1002334'
SELECT * FROM PRODUTOS WHERE [CÓDIGO] = '1002334'

UPDATE [SUCOS_VENDAS].DBO.[TABELA DE PRODUTOS]
SET [PREÇO DE LISTA] = 8
WHERE [CODIGO DO PRODUTO] = '1002334'

MERGE INTO PRODUTOS A
USING [SUCOS_VENDAS].dbo.[TABELA DE PRODUTOS] B
ON A.[CÓDIGO] = B.[CODIGO DO PRODUTO]
AND A.[CÓDIGO] = '1002334'
WHEN MATCHED THEN
UPDATE SET A.[PREÇO LISTA] = B.[PREÇO DE LISTA];

SELECT * FROM [SUCOS_VENDAS].dbo.[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1002334'
SELECT * FROM PRODUTOS WHERE [CÓDIGO] = '1002334'

SELECT C.NOME, C.BAIRRO, C.[VOLUME COMPRA], V.NOME, V.BAIRRO FROM CLIENTES C
INNER JOIN VENDEDORES V
ON C.BAIRRO = V.BAIRRO

MERGE INTO CLIENTES C
USING VENDEDORES V
ON C.BAIRRO = V.BAIRRO
WHEN MATCHED THEN
UPDATE SET C.[VOLUME COMPRA] = C.[VOLUME COMPRA] * 1.3;

SELECT [CODIGO DO PRODUTO] FROM SUCOS_VENDAS.DBO.[TABELA DE PRODUTOS]

SELECT CÓDIGO FROM PRODUTOS

SELECT * FROM PRODUTOS WHERE CÓDIGO NOT IN (SELECT [CODIGO DO PRODUTO] FROM SUCOS_VENDAS.DBO.[TABELA DE PRODUTOS])

DELETE FROM PRODUTOS WHERE CÓDIGO NOT IN (SELECT [CODIGO DO PRODUTO] FROM SUCOS_VENDAS.DBO.[TABELA DE PRODUTOS])

SELECT * FROM NOTAS
SELECT * FROM CLIENTES WHERE CPF = '9999999999'

DELETE FROM CLIENTES WHERE CPF = '9999999999'

---

CREATE TABLE TAB_IDENTITY
(ID INT IDENTITY (1,1) NOT NULL,
DESCRITOR VARCHAR(20) NULL)

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE X')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE Y')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE Z')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE A')

SELECT * FROM TAB_IDENTITY

DELETE FROM TAB_IDENTITY WHERE ID = 1

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE B')

DROP TABLE TAB_IDENTITY

CREATE TABLE TAB_IDENTITY
(ID INT IDENTITY (100,5) NOT NULL,
DESCRITOR VARCHAR(20) NULL)

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE X')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE Y')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE Z')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE A')

SELECT * FROM TAB_IDENTITY

CREATE TABLE TAB_PADRAO (
ID INT IDENTITY (1,1) NOT NULL,
DESCRITOR VARCHAR (50),
ENDERECO VARCHAR (200),
CIDADE VARCHAR (50) DEFAULT 'Cidade Não Definida',
DATA_CRIACAO DATE DEFAULT GETDATE()
)

INSERT INTO TAB_PADRAO (DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO)
VALUES ('CLIENTE X', 'RUA PROJETADA A', 'SÃO PAULO', '20180430')

SELECT * FROM TAB_PADRAO

INSERT INTO TAB_PADRAO (DESCRITOR)
VALUES ('CLIENTE Y')

---

CREATE TRIGGER TG_ITENS_VENDIDOS
ON [ITENS VENDIDOS]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN

DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO (DATA_VENDA, TOTAL_VENDA)
SELECT A.DATA AS DATA_VENDA, SUM(B.QUANTIDADE * B.[PREÇO]) AS TOTAL_VENDA
FROM NOTAS A INNER JOIN [ITENS VENDIDOS] B
ON A.NÚMERO = B.NÚMERO
GROUP BY A.DATA;

END;

INSERT INTO [NOTAS] ([NÚMERO], DATA, CPF, MATRÍCULA, IMPOSTO)
VALUES ('0100', '2018-05-15', '1471156710', '235', 0.18)

INSERT INTO [ITENS VENDIDOS] ([NÚMERO],[CÓDIGO],[QUANTIDADE],[PREÇO])
VALUES ('0100', '1000889', 100, 1)
INSERT INTO [ITENS VENDIDOS] ([NÚMERO],[CÓDIGO],[QUANTIDADE],[PREÇO])
VALUES ('0100', '1002334', 100, 1)

SELECT * FROM TAB_FATURAMENTO

INSERT INTO [NOTAS] ([NÚMERO], DATA, CPF, MATRÍCULA, IMPOSTO)
VALUES ('0101', '2018-05-15', '1471156710', '235', 0.18)

INSERT INTO [ITENS VENDIDOS] ([NÚMERO],[CÓDIGO],[QUANTIDADE],[PREÇO])
VALUES ('0101', '1000889', 100, 1)
INSERT INTO [ITENS VENDIDOS] ([NÚMERO],[CÓDIGO],[QUANTIDADE],[PREÇO])
VALUES ('0101', '1002334', 100, 1)

INSERT INTO [NOTAS] ([NÚMERO], DATA, CPF, MATRÍCULA, IMPOSTO)
VALUES ('0102', '2018-05-16', '1471156710', '235', 0.18)

INSERT INTO [ITENS VENDIDOS] ([NÚMERO],[CÓDIGO],[QUANTIDADE],[PREÇO])
VALUES ('0102', '1000889', 300, 1.5)
INSERT INTO [ITENS VENDIDOS] ([NÚMERO],[CÓDIGO],[QUANTIDADE],[PREÇO])
VALUES ('0102', '1002334', 200, 1)

DELETE FROM [ITENS VENDIDOS] WHERE [NÚMERO] = '0102' AND [CÓDIGO] = '1002334'

UPDATE [ITENS VENDIDOS] SET [QUANTIDADE] = 300 WHERE [NÚMERO] = '0102' AND [CÓDIGO] = '1000889'

CREATE TRIGGER TG_CLIENTES_IDADE
ON CLIENTES
AFTER INSERT, UPDATE, DELETE
AS 
BEGIN
UPDATE CLIENTES SET
IDADE = DATEDIFF(YEAR, [DATA NASCIMENTO], GETDATE());
END;

---

CREATE TABLE TAB_CHECK (
ID INT NOT NULL,
NOME VARCHAR(20) NULL,
IDADE INT NULL,
CIDADE VARCHAR(20) NULL,
CONSTRAINT CHK_PESSOAS CHECK (IDADE >= 18)
)

INSERT INTO TAB_CHECK (ID, NOME, IDADE, CIDADE)
VALUES (1, 'JOÃO', 19, 'RIO DE JANEIRO')

SELECT * FROM TAB_CHECK

INSERT INTO TAB_CHECK (ID, NOME, IDADE, CIDADE)
VALUES (2, 'PEDRO', 17, 'SÃO PAULO')
