SELECT * FROM [TABELA DE CLIENTES]
SELECT * FROM [ITENS NOTAS FISCAIS]
SELECT * FROM [NOTAS FISCAIS]

SELECT NF.CPF, NF.DATA, INF.QUANTIDADE
FROM [NOTAS FISCAIS] NF INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO

SELECT NF.CPF, CONVERT(VARCHAR, NF.DATA, 120), INF.QUANTIDADE
FROM [NOTAS FISCAIS] NF INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO

SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1,7) AS 'ANO_MES', INF.QUANTIDADE
FROM [NOTAS FISCAIS] NF INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO

SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1,7) AS 'ANO_MES', SUM(INF.QUANTIDADE) AS 'QNTD_MES'
FROM [NOTAS FISCAIS] NF INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1,7)

SELECT TC.NOME, CMES.ANO_MES, CMES.QNTD_MES, TC.[VOLUME DE COMPRA]
FROM (SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1,7) AS 'ANO_MES', SUM(INF.QUANTIDADE) AS 'QNTD_MES'
FROM [NOTAS FISCAIS] NF INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1,7)) CMES
INNER JOIN [TABELA DE CLIENTES] TC
ON CMES.CPF = TC.CPF


SELECT VOLUME_COMPRAS.NOME,VOLUME_COMPRAS.ANO_MES, VOLUME_COMPRAS.QNTD_MES, VOLUME_COMPRAS.[VOLUME DE COMPRA],
CASE WHEN VOLUME_COMPRAS.QNTD_MES <= VOLUME_COMPRAS.[VOLUME DE COMPRA] THEN 'COMPRA VÁLIDA'
WHEN VOLUME_COMPRAS.QNTD_MES > VOLUME_COMPRAS.[VOLUME DE COMPRA] THEN 'COMPRA INVÁLIDA'
END AS 'VALIDACAO'
FROM
(SELECT TC.NOME, CMES.ANO_MES, CMES.QNTD_MES, TC.[VOLUME DE COMPRA]
FROM (SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1,7) AS 'ANO_MES', SUM(INF.QUANTIDADE) AS 'QNTD_MES'
FROM [NOTAS FISCAIS] NF INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1,7)) CMES
INNER JOIN [TABELA DE CLIENTES] TC
ON CMES.CPF = TC.CPF) VOLUME_COMPRAS
ORDER BY VOLUME_COMPRAS.NOME, VOLUME_COMPRAS.ANO_MES

SELECT VOLUME_COMPRAS.NOME,VOLUME_COMPRAS.ANO_MES, VOLUME_COMPRAS.QNTD_MES, VOLUME_COMPRAS.[VOLUME DE COMPRA],
ROUND(((1 - (VOLUME_COMPRAS.[VOLUME DE COMPRA] / VOLUME_COMPRAS.QNTD_MES)) * 100), 2) AS 'DIFERENÇA (%)',
CASE WHEN VOLUME_COMPRAS.QNTD_MES <= VOLUME_COMPRAS.[VOLUME DE COMPRA] THEN 'COMPRA VÁLIDA'
WHEN VOLUME_COMPRAS.QNTD_MES > VOLUME_COMPRAS.[VOLUME DE COMPRA] THEN 'COMPRA INVÁLIDA'
END AS 'VALIDACAO'
FROM
(SELECT TC.NOME, CMES.ANO_MES, CMES.QNTD_MES, TC.[VOLUME DE COMPRA]
FROM (SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1,7) AS 'ANO_MES', SUM(INF.QUANTIDADE) AS 'QNTD_MES'
FROM [NOTAS FISCAIS] NF INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1,7)) CMES
INNER JOIN [TABELA DE CLIENTES] TC
ON CMES.CPF = TC.CPF) VOLUME_COMPRAS
WHERE VOLUME_COMPRAS.QNTD_MES > VOLUME_COMPRAS.[VOLUME DE COMPRA
ORDER BY VOLUME_COMPRAS.NOME, VOLUME_COMPRAS.ANO_MES

SELECT VOLUME_COMPRAS.NOME, VOLUME_COMPRAS.ANO_MES, VOLUME_COMPRAS.QNTD_MES, VOLUME_COMPRAS.[VOLUME DE COMPRA],
CONVERT(DECIMAL(15,2), ((1 - (VOLUME_COMPRAS.[VOLUME DE COMPRA] / VOLUME_COMPRAS.QNTD_MES)) * 100)) AS 'DIFERENÇA (%)',
CASE WHEN VOLUME_COMPRAS.QNTD_MES <= VOLUME_COMPRAS.[VOLUME DE COMPRA] THEN 'COMPRA VÁLIDA'
WHEN VOLUME_COMPRAS.QNTD_MES > VOLUME_COMPRAS.[VOLUME DE COMPRA] THEN 'COMPRA INVÁLIDA'
END AS 'VALIDACAO'
FROM
(SELECT TC.NOME, CMES.ANO_MES, CMES.QNTD_MES, TC.[VOLUME DE COMPRA]
FROM (SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1,7) AS 'ANO_MES', SUM(INF.QUANTIDADE) AS 'QNTD_MES'
FROM [NOTAS FISCAIS] NF INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1,7)) CMES
INNER JOIN [TABELA DE CLIENTES] TC
ON CMES.CPF = TC.CPF) VOLUME_COMPRAS
WHERE VOLUME_COMPRAS.QNTD_MES > VOLUME_COMPRAS.[VOLUME DE COMPRA]
ORDER BY VOLUME_COMPRAS.NOME, VOLUME_COMPRAS.ANO_MES

--------------------------------------------

select * from [TABELA DE PRODUTOS]
select * from [ITENS NOTAS FISCAIS]
select * from [NOTAS FISCAIS]

select TP.SABOR, YEAR(DATA) as 'ANO', SUM(INF.QUANTIDADE * INF.PREÇO) as 'FATURAMENTO' 
from [ITENS NOTAS FISCAIS] INF
inner join [NOTAS FISCAIS] NF on INF.NUMERO = NF.NUMERO
inner join [TABELA DE PRODUTOS] TP on INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
where YEAR(DATA) = '2016'
group by TP.SABOR, YEAR(DATA)

select YEAR(DATA) as 'ANO', SUM(INF.QUANTIDADE * INF.PREÇO) as 'FATURAMENTO' 
from [ITENS NOTAS FISCAIS] INF
inner join [NOTAS FISCAIS] NF on INF.NUMERO = NF.NUMERO
inner join [TABELA DE PRODUTOS] TP on INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
where YEAR(DATA) = '2016'
group by YEAR(DATA)

select * from [TABELA DE PRODUTOS]
select * from [ITENS NOTAS FISCAIS]
select * from [NOTAS FISCAIS]

select AUX1.SABOR, AUX1.ANO, CONVERT(DECIMAL(15,2),(AUX1.FATURAMENTO)) as 'FATURAMENTO', CONVERT(DECIMAL(15,2),((AUX1.FATURAMENTO / AUX2.TFATURAMENTO) * 100)) as '%'
from
(select TP.SABOR, YEAR(DATA) as 'ANO', SUM(INF.QUANTIDADE * INF.PREÇO) as 'FATURAMENTO' 
from [ITENS NOTAS FISCAIS] INF
inner join [NOTAS FISCAIS] NF on INF.NUMERO = NF.NUMERO
inner join [TABELA DE PRODUTOS] TP on INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
where YEAR(DATA) = '2016'
group by TP.SABOR, YEAR(DATA)) AUX1
inner join 
(select YEAR(DATA) as 'ANO', SUM(INF.QUANTIDADE * INF.PREÇO) as 'TFATURAMENTO' 
from [ITENS NOTAS FISCAIS] INF
inner join [NOTAS FISCAIS] NF on INF.NUMERO = NF.NUMERO
inner join [TABELA DE PRODUTOS] TP on INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
where YEAR(DATA) = '2016'
group by YEAR(DATA)) AUX2
on AUX1.ANO = AUX2.ANO
order by FATURAMENTO desc

select AUX1.TAMANHO, AUX1.ANO, CONVERT(DECIMAL(15,2),(AUX1.FATURAMENTO)) as 'FATURAMENTO', CONVERT(DECIMAL(15,2),((AUX1.FATURAMENTO / AUX2.TFATURAMENTO) * 100)) as '%'
from
(select TP.TAMANHO, YEAR(DATA) as 'ANO', SUM(INF.QUANTIDADE * INF.PREÇO) as 'FATURAMENTO' 
from [ITENS NOTAS FISCAIS] INF
inner join [NOTAS FISCAIS] NF on INF.NUMERO = NF.NUMERO
inner join [TABELA DE PRODUTOS] TP on INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
where YEAR(DATA) = '2016'
group by TP.TAMANHO, YEAR(DATA)) AUX1
inner join 
(select YEAR(DATA) as 'ANO', SUM(INF.QUANTIDADE * INF.PREÇO) as 'TFATURAMENTO' 
from [ITENS NOTAS FISCAIS] INF
inner join [NOTAS FISCAIS] NF on INF.NUMERO = NF.NUMERO
inner join [TABELA DE PRODUTOS] TP on INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
where YEAR(DATA) = '2016'
group by YEAR(DATA)) AUX2
on AUX1.ANO = AUX2.ANO
order by FATURAMENTO desc